# Generated by Django 2.0.6 on 2018-06-18 00:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('path', models.CharField(max_length=300)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=200)),
                ('destiny', models.CharField(max_length=200)),
                ('distance', models.FloatField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('map_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortest_route_app.Map')),
            ],
        ),
    ]
