# Generated by Django 2.0.6 on 2018-06-20 02:37

from django.db import migrations, models
import shortest_route_app.models
from shortest_route_app.models.FileMap import validate_file


class Migration(migrations.Migration):

    dependencies = [
        ('shortest_route_app', '0002_auto_20180618_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='minimum_route',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filemap',
            name='file',
            field=models.FileField(upload_to='maps/', validators=[validate_file]),
        ),
    ]
