# Generated by Django 2.0.6 on 2018-06-22 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortest_route_app', '0003_auto_20180619_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='destiny',
            new_name='destination',
        ),
    ]
